name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - firmware/**
  pull_request:
    branches: [ "master" ]
    paths:
      - firmware/**

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust target
      run: rustup target add thumbv6m-none-eabi
    - name: Build
      working-directory: firmware
      run: cargo build --verbose
